// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Biblioteca___C_.Context;

#nullable disable

namespace Sistema_de_Biblioteca___C_.Migrations
{
    [DbContext(typeof(BiblioContext))]
    [Migration("20260302172900_userMigration")]
    partial class userMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Biblioteca___C_.Models.Livro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Descricao");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Nome");

                    b.Property<string>("nomeAutor")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Autor");

                    b.HasKey("id");

                    b.ToTable("livros");
                });

            modelBuilder.Entity("Sistema_de_Biblioteca___C_.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasJsonPropertyName("UserId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("password");

                    b.Property<string>("userName")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("userName");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
