// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sistema_de_Biblioteca___C_.Context;

#nullable disable

namespace Sistema_de_Biblioteca___C_.Migrations
{
    [DbContext(typeof(BiblioContext))]
    partial class BiblioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sistema_de_Biblioteca___C_.Models.Livro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("desc")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Descricao");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Nome");

                    b.Property<string>("nomeAutor")
                        .HasColumnType("nvarchar(max)")
                        .HasJsonPropertyName("Autor");

                    b.HasKey("id");

                    b.ToTable("livros");
                });
#pragma warning restore 612, 618
        }
    }
}
